sudo: enabled

services:
  - docker

install: docker build -t dummy-webserver .
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag dummery-webserver $DOCKER_USERNAME/dummy-webserver
  - docker push $DOCKER_USERNAME/dummy-webserver
